@testitem "Generic" tags=[:FrankCopula] setup=[M] begin M.check(FrankCopula(2,0.5)) end
@testitem "Generic" tags=[:FrankCopula] setup=[M] begin M.check(FrankCopula(2,1-log(rand(M.rng)))) end
@testitem "Generic" tags=[:FrankCopula] setup=[M] begin M.check(FrankCopula(2,1.0)) end
@testitem "Generic" tags=[:FrankCopula] setup=[M] begin M.check(FrankCopula(2,-5)) end
@testitem "Generic" tags=[:FrankCopula] setup=[M] begin M.check(FrankCopula(3,1-log(rand(M.rng)))) end
@testitem "Generic" tags=[:FrankCopula] setup=[M] begin M.check(FrankCopula(3,1.0)) end
@testitem "Generic" tags=[:FrankCopula] setup=[M] begin M.check(FrankCopula(3,12)) end
@testitem "Generic" tags=[:FrankCopula] setup=[M] begin M.check(FrankCopula(4,1-log(rand(M.rng)))) end
@testitem "Generic" tags=[:FrankCopula] setup=[M] begin M.check(FrankCopula(4,1.0)) end
@testitem "Generic" tags=[:FrankCopula] setup=[M] begin M.check(FrankCopula(4,150)) end
@testitem "Generic" tags=[:FrankCopula] setup=[M] begin M.check(FrankCopula(4,30)) end
@testitem "Generic" tags=[:FrankCopula] setup=[M] begin M.check(FrankCopula(4,37)) end
@testitem "Generic" tags=[:FrankCopula] setup=[M] begin M.check(FrankCopula(4,6.)) end
@testitem "Generic" tags=[:FrankCopula] setup=[M] begin M.check(FrankCopula(4,6)) end