@testitem "Generic" tags=[:HuslerReissCopula] setup=[M] begin M.check(HuslerReissCopula(0.0)) end
@testitem "Generic" tags=[:HuslerReissCopula] setup=[M] begin M.check(HuslerReissCopula(0.1)) end
@testitem "Generic" tags=[:HuslerReissCopula] setup=[M] begin M.check(HuslerReissCopula(0.256693308150987)) end
@testitem "Generic" tags=[:HuslerReissCopula] setup=[M] begin M.check(HuslerReissCopula(1+4*rand(M.rng))) end
@testitem "Generic" tags=[:HuslerReissCopula] setup=[M] begin M.check(HuslerReissCopula(5+5*rand(M.rng))) end
@testitem "Generic" tags=[:HuslerReissCopula] setup=[M] begin M.check(HuslerReissCopula(rand(M.rng))) end
@testitem "Generic" tags=[:HuslerReissCopula] setup=[M] begin M.check(HuslerReissCopula(3.5)) end
@testitem "Generic" tags=[:HuslerReissCopula] setup=[M] begin M.check(HuslerReissCopula(1.6287031392529938)) end
@testitem "Generic" tags=[:HuslerReissCopula] setup=[M] begin M.check(HuslerReissCopula(5.319851350643586)) end
@testitem "Generic" tags=[:HuslerReissCopula] setup=[M] begin M.check(HuslerReissCopula(Inf)) end
