_supports_liouville_order(G::Generator, order::Real) = ceil(Int, order) <= max_monotony(G)
_supports_liouville_order(G::𝒲, order::Real) = order <= G.order

"""
    LiouvilleCopula{d}(G::Generator, α)
    LiouvilleCopula(G::Generator, α)

Liouville copula generated by `G` with positive Dirichlet parameters `α`.
Writing `α₀ = sum(α)`, its underlying Liouville vector is `R * D`, where
`R ∼ 𝒲₋₁(G, α₀)` and `D ∼ Dirichlet(α)` are independent. The copula is the
survival copula of `R * D`; in particular, `α = ones(d)` recovers the
Archimedean copula generated by `G`.

For a general generator, every positive real parameter vector is supported when
`ceil(sum(α)) <= max_monotony(G)`. A `𝒲(R, source_order)` generator directly
supports every `sum(α) <= source_order`, without rounding. Integer-valued orders
retain their specialized Williamson inverse methods; other orders use exact
beta reductions. The radial `R` may be any supported non-negative univariate
distribution. When `α == ones(d)`, the resulting `LiouvilleCopula` is exactly
the Archimedean copula generated by `G`; evaluation uses that identity while
the concrete Liouville family type is retained.

Sampling uses the radial-Dirichlet representation. Density and distribution
evaluation follow `Distributions.jl`; the bivariate CDF uses a one-dimensional
radial/Beta expectation, while higher dimensions integrate a stick-breaking
representation of the Dirichlet direction. Selecting dimensions keeps `G` and
the corresponding entries of `α`, so the required lower order is recovered
without changing the model representation.

Conditioning also preserves the Liouville family. When `G` has a frailty, both
integer and non-integer conditioned orders use its exact power-exponentially
tilted posterior distribution. Otherwise, integer-valued sums reuse
`TiltedGenerator` and non-integer sums use an exact conditional-radial
representation. These paths provide conditional distributions and the
Rosenblatt and inverse Rosenblatt transforms without differentiating the
Liouville CDF numerically.

See also the documentation example “Liouville copulas with real Dirichlet
parameters”.
"""
struct LiouvilleCopula{d,TG,Tα} <: Copula{d}
    G::TG
    α::NTuple{d,Tα}
    function LiouvilleCopula{d}(G::Generator, α) where {d}
        d >= 2 || throw(ArgumentError("a Liouville copula must have dimension at least 2"))
        length(α) == d || throw(ArgumentError("expected $d Dirichlet parameters, got $(length(α))"))
        αtuple = promote(map(float, α)...)
        all(a -> isfinite(a) && a > 0, αtuple) || throw(ArgumentError("Dirichlet parameters must be finite and positive"))
        α₀ = sum(αtuple)
        _supports_liouville_order(G, α₀) || throw(ArgumentError("the generator $G cannot provide the required Williamson order sum(α) = $α₀"))
        return new{d,typeof(G),eltype(αtuple)}(G, αtuple)
    end
end

LiouvilleCopula(G::Generator, α) = LiouvilleCopula{length(α)}(G, α)
LiouvilleCopula(d::Integer, G::Generator, α) = LiouvilleCopula{d}(G, α)

Distributions.params(C::LiouvilleCopula) = (; G = C.G, α = C.α)

_liouville_order(C::LiouvilleCopula) = sum(C.α)
_liouville_radial(C::LiouvilleCopula) = 𝒲₋₁(C.G, _liouville_order(C))
_liouville_margin(C::LiouvilleCopula, i::Integer) = 𝒲₋₁(C.G, C.α[i])
copula_measure_style(C::LiouvilleCopula) =
    radial_measure_style(C.G, _liouville_order(C))
function _liouville_coordinates(C::LiouvilleCopula{d}, u) where {d}
    margins = ntuple(i -> 𝒲₋₁(C.G, C.α[i]), d)
    x = ntuple(i -> Distributions.quantile(margins[i], 1 - u[i]), d)
    return margins, x
end

function Distributions._rand!(
    rng::Distributions.AbstractRNG,
    C::LiouvilleCopula{d},
    A::AbstractMatrix{T},
) where {d,T<:Real}
    size(A, 1) == d || throw(ArgumentError("Dimension mismatch between copula and output matrix"))
    all(isone, C.α) &&
        return Distributions._rand!(rng, ArchimedeanCopula{d}(C.G), A)
    radial = _liouville_radial(C)
    simplex = Distributions.Dirichlet(collect(C.α))
    margins = ntuple(i -> _liouville_margin(C, i), d)
    direction = Vector{T}(undef, d)

    @inbounds for col in axes(A, 2)
        Random.rand!(rng, simplex, direction)
        r = rand(rng, radial)
        for row in axes(A, 1)
            A[row, col] = Distributions.ccdf(margins[row], r * direction[row])
        end
    end
    return A
end

function _cdf(C::LiouvilleCopula{2}, u)
    all(isone, C.α) && return Distributions.cdf(ArchimedeanCopula{2}(C.G), u)
    isone(u[1]) && return u[2]
    isone(u[2]) && return u[1]
    _, x = _liouville_coordinates(C, u)
    radial = 𝒲₋₁(C.G, _liouville_order(C))
    beta = Distributions.Beta(C.α...)
    xsum = sum(x)

    value = Distributions.expectation(radial) do r
        r <= xsum && return zero(float(r + xsum))
        lo = Distributions.cdf(beta, x[1] / r)
        hi = Distributions.cdf(beta, 1 - x[2] / r)
        return max(zero(hi - lo), hi - lo)
    end
    return clamp(value, zero(value), one(value))
end

function _cdf(C::LiouvilleCopula{d}, u) where {d}
    all(isone, C.α) && return Distributions.cdf(ArchimedeanCopula{d}(C.G), u)
    # TODO: When all Dirichlet parameters are integers, replace this cubature
    # with the corresponding exact finite-sum expression.
    _, x = _liouville_coordinates(C, u)
    radial = 𝒲₋₁(C.G, _liouville_order(C))
    betas = ntuple(i -> Distributions.Beta(C.α[i], sum(C.α[(i + 1):d])), d - 1)
    T = float(promote_type(eltype(u), eltype(C.α)))

    function integrand(z)
        any(t -> iszero(t) || isone(t), z) && return zero(T)
        remaining = one(T)
        threshold = zero(T)
        @inbounds for i in 1:(d - 1)
            v = Distributions.quantile(betas[i], z[i])
            direction = remaining * v
            threshold = max(threshold, x[i] / direction)
            remaining *= 1 - v
        end
        threshold = max(threshold, x[d] / remaining)
        return Distributions.ccdf(radial, threshold)
    end

    value = HCubature.hcubature(integrand, zeros(T, d - 1), ones(T, d - 1); rtol=sqrt(eps(T)))[1]
    return clamp(value, zero(value), one(value))
end

function Distributions._logpdf(C::LiouvilleCopula{d}, u) where {d}
    all(isone, C.α) && return Distributions.logpdf(ArchimedeanCopula{d}(C.G), u)
    all(x -> 0 < x < 1, u) || return eltype(u)(-Inf)

    radial = 𝒲₋₁(C.G, _liouville_order(C))
    margins, x = _liouville_coordinates(C, u)
    r = sum(x)
    α₀ = _liouville_order(C)
    radial_density = Distributions.pdf(radial, r)
    isfinite(radial_density) && radial_density > 0 || return eltype(u)(-Inf)
    margin_densities = ntuple(i -> Distributions.pdf(margins[i], x[i]), d)
    all(f -> isfinite(f) && f > 0, margin_densities) || return eltype(u)(-Inf)

    value = SpecialFunctions.loggamma(α₀) - sum(SpecialFunctions.loggamma, C.α)
    value += log(radial_density) + (1 - α₀) * log(r)
    value += sum(i -> (C.α[i] - 1) * log(x[i]) - log(margin_densities[i]), 1:d)
    return value
end

# Radial representation of a fractional tilt. For X = R * D_α and fixed
# X_J = x_J, the sum S of the remaining coordinates has density proportional
# to f_R(S+s_J) * (S+s_J)^(1-α₀) * S^(α_I-1).
struct LiouvilleConditionalRadial{TR,TS,TA0,TAI,TN} <: Distributions.ContinuousUnivariateDistribution
    radial::TR
    shift::TS
    source_order::TA0
    target_order::TAI
    normalizer::TN
    integration_knots::Vector{TN}
    cumulative_masses::Vector{TN}

    function LiouvilleConditionalRadial(radial::TR, shift::TS, source_order::TA0, target_order::TAI) where {TR,TS,TA0,TAI}
        upper = Base.maximum(radial) - shift
        upper > 0 || throw(ArgumentError("the conditioning point is outside the radial support"))
        T = typeof(float(shift + source_order + target_order))
        transformed_kernel(t) = _liouville_conditional_transformed_kernel(radial, shift, source_order, target_order, upper, t)
        normalizer, _, segments = QuadGK.quadgk_segbuf(transformed_kernel, zero(T), one(T); rtol=sqrt(eps(T)))
        isfinite(normalizer) && normalizer > 0 || throw(ArgumentError("the conditioning event has zero or non-finite density"))
        sort!(segments; by=segment -> segment.a)
        integration_knots = [first(segments).a; map(segment -> segment.b, segments)]
        cumulative_masses = [zero(normalizer); cumsum(map(segment -> segment.I, segments))]
        cumulative_masses[end] = normalizer
        return new{TR,TS,TA0,TAI,typeof(normalizer)}(
            radial, shift, source_order, target_order, normalizer,
            integration_knots, cumulative_masses,
        )
    end
end

function _liouville_conditional_transformed_kernel(
    radial, shift, source_order, target_order, upper, t,
)
    if isfinite(upper)
        s = upper * t
        jacobian = upper
    else
        denominator = 1 - t
        s = t / denominator
        jacobian = inv(denominator^2)
    end
    return _liouville_conditional_kernel(
        radial, shift, source_order, target_order, s,
    ) * jacobian
end

function _liouville_conditional_unit_coordinate(D::LiouvilleConditionalRadial, s)
    upper = maximum(D)
    return isfinite(upper) ? s / upper : s / (1 + s)
end

function _liouville_conditional_radial_coordinate(D::LiouvilleConditionalRadial, t)
    upper = maximum(D)
    return isfinite(upper) ? upper * t : t / (1 - t)
end

function _liouville_conditional_cached_integral(D::LiouvilleConditionalRadial, t)
    knots = D.integration_knots
    masses = D.cumulative_masses
    segment = min(searchsortedlast(knots, t), length(knots) - 1)
    base = masses[segment]
    t == knots[segment] && return base
    upper = maximum(D)
    partial = QuadGK.quadgk(
        x -> _liouville_conditional_transformed_kernel(
            D.radial, D.shift, D.source_order, D.target_order, upper, x,
        ),
        knots[segment], t;
        rtol=sqrt(eps(typeof(float(t)))),
    )[1]
    return base + partial
end

function _liouville_conditional_kernel(radial, shift, source_order, target_order, s)
    s < 0 && return zero(float(s))
    r = s + shift
    return Distributions.pdf(radial, r) * r^(1 - source_order) * s^(target_order - 1)
end

Base.minimum(D::LiouvilleConditionalRadial) = zero(float(D.shift))
Base.maximum(D::LiouvilleConditionalRadial) = Base.maximum(D.radial) - D.shift
function Distributions.pdf(D::LiouvilleConditionalRadial, s::Real)
    minimum(D) <= s <= maximum(D) || return zero(float(s))
    return _liouville_conditional_kernel(
        D.radial, D.shift, D.source_order, D.target_order, s,
    ) / D.normalizer
end
Distributions.logpdf(D::LiouvilleConditionalRadial, s::Real) = log(Distributions.pdf(D, s))
function Distributions.cdf(D::LiouvilleConditionalRadial, s::Real)
    s <= minimum(D) && return zero(float(s))
    s >= maximum(D) && return one(float(s))
    t = _liouville_conditional_unit_coordinate(D, s)
    value = _liouville_conditional_cached_integral(D, t) / D.normalizer
    return clamp(value, zero(value), one(value))
end
function Distributions.quantile(D::LiouvilleConditionalRadial, p::Real)
    0 <= p <= 1 || throw(ArgumentError("p must be in [0, 1]"))
    iszero(p) && return minimum(D)
    isone(p) && return maximum(D)
    target = p * D.normalizer
    segment = min(
        searchsortedlast(D.cumulative_masses, target),
        length(D.integration_knots) - 1,
    )
    a, b = D.integration_knots[segment], D.integration_knots[segment + 1]
    base, total = D.cumulative_masses[segment], D.cumulative_masses[segment + 1]
    objective(t) = t == a ? base - target :
                   t == b ? total - target :
                   _liouville_conditional_cached_integral(D, t) - target
    t = Roots.find_zero(objective, (a, b), Roots.Brent())
    return _liouville_conditional_radial_coordinate(D, t)
end
Distributions.rand(rng::Distributions.AbstractRNG, D::LiouvilleConditionalRadial) =
    Distributions.quantile(D, rand(rng))

struct LiouvilleDistortion{TM,TCM} <: Distortion
    margin::TM
    conditional_margin::TCM
end

function Distributions.cdf(D::LiouvilleDistortion, u::Real)
    u <= 0 && return zero(float(u))
    u >= 1 && return one(float(u))
    x = Distributions.quantile(D.margin, 1 - u)
    return Distributions.ccdf(D.conditional_margin, x)
end
function Distributions.quantile(D::LiouvilleDistortion, p::Real)
    0 <= p <= 1 || throw(ArgumentError("p must be in [0, 1]"))
    iszero(p) && return zero(float(p))
    isone(p) && return one(float(p))
    x = Distributions.quantile(D.conditional_margin, 1 - p)
    return Distributions.ccdf(D.margin, x)
end
function Distributions.logpdf(D::LiouvilleDistortion, u::Real)
    0 < u < 1 || return -Inf
    x = Distributions.quantile(D.margin, 1 - u)
    return log(Distributions.pdf(D.conditional_margin, x)) -
           log(Distributions.pdf(D.margin, x))
end

function _liouville_conditional_components(
    C::LiouvilleCopula{D}, js::NTuple{p,Int}, uⱼₛ::NTuple{p,<:Real},
) where {D,p}
    is = Tuple(i for i in 1:D if i ∉ js)
    source_order = _liouville_order(C)
    target_order = sum(C.α[i] for i in is)
    tilted_order = sum(C.α[j] for j in js)
    original_margins = ntuple(i -> 𝒲₋₁(C.G, C.α[i]), D)
    xⱼₛ = ntuple(k -> Distributions.quantile(original_margins[js[k]], 1 - uⱼₛ[k]), p)
    shift = sum(xⱼₛ)

    source_frailty = frailty(C.G)
    conditional_generator = if source_frailty !== nothing
        conditional_frailty = PowerTiltedFrailty(source_frailty, tilted_order, shift)
        conditional_radial = WilliamsonFromFrailty(conditional_frailty, target_order)
        𝒲(conditional_radial, target_order)
    elseif isinteger(tilted_order)
        TiltedGenerator(C.G, Int(tilted_order), shift)
    else
        source_radial = 𝒲₋₁(C.G, source_order)
        conditional_radial = LiouvilleConditionalRadial(
            source_radial, shift, source_order, target_order,
        )
        𝒲(conditional_radial, target_order)
    end

    conditional_margins = ntuple(
        k -> 𝒲₋₁(conditional_generator, C.α[is[k]]),
        length(is),
    )
    distortions = ntuple(
        k -> LiouvilleDistortion(original_margins[is[k]], conditional_margins[k]),
        length(is),
    )
    conditional_copula = length(is) == 1 ? nothing : LiouvilleCopula{length(is)}(
        conditional_generator, ntuple(k -> C.α[is[k]], length(is)),
    )
    return conditional_copula, distortions, is
end

function DistortionFromCop(
    C::LiouvilleCopula,
    js::NTuple{p,Int},
    uⱼₛ::NTuple{p,<:Real},
    i::Int,
) where {p}
    _, distortions, is = _liouville_conditional_components(C, js, uⱼₛ)
    position = findfirst(==(i), is)
    position === nothing && throw(ArgumentError("the target dimension is conditioned"))
    return distortions[position]
end

function ConditionalCopula(C::LiouvilleCopula, js, uⱼₛ)
    conditional_copula, _, _ = _liouville_conditional_components(C, js, uⱼₛ)
    conditional_copula === nothing && throw(ArgumentError(
        "conditioning leaves one margin and therefore no conditional copula",
    ))
    return conditional_copula
end

# `condition` needs both the conditional copula and all marginal distortions,
# whereas Rosenblatt and one-dimensional conditioning request individual
# distortions through `DistortionFromCop`. Specializing this shared hook avoids
# rebuilding (and renormalizing) the same conditional frailty or radial once
# for the copula and once per remaining margin. We still define
# `ConditionalCopula` and `DistortionFromCop` above because they are independent
# extension points used directly by the generic conditioning interface.
function _conditional_components(C::LiouvilleCopula, js, uⱼₛ, is)
    conditional_copula, distortions, computed_is =
        _liouville_conditional_components(C, js, uⱼₛ)
    computed_is == is || throw(ArgumentError("inconsistent conditioning dimensions"))
    return conditional_copula, distortions
end

SubsetCopula(C::LiouvilleCopula, dims::NTuple{p,Int}) where {p} =
    LiouvilleCopula{p}(C.G, ntuple(i -> C.α[dims[i]], p))

_available_fitting_methods(::Type{<:LiouvilleCopula}, d) = Tuple{}()
