_supports_liouville_order(G::Generator, order::Real) = ceil(Int, order) <= max_monotony(G)
_supports_liouville_order(G::𝒲, order::Real) = order <= G.order

"""
    LiouvilleCopula{d}(G::Generator, α)
    LiouvilleCopula(d, G::Generator, α)
    LiouvilleCopula(G::Generator, α)

Liouville copula generated by `G` with positive Dirichlet parameters `α`.
Writing `α₀ = sum(α)`, its underlying Liouville vector is `R * D`, where
`R ∼ 𝒲₋₁(G, α₀)` and `D ∼ Dirichlet(α)` are independent. The copula is the
survival copula of `R * D`; in particular, `α = ones(d)` recovers the
Archimedean copula generated by `G`.

For a general generator, every positive real parameter vector is supported when
`ceil(sum(α)) <= max_monotony(G)`. A `𝒲(R, source_order)` generator directly
supports every `sum(α) <= source_order`, without rounding. Integer-valued orders
retain their specialized Williamson inverse methods; other orders use exact
beta reductions. The radial `R` may be any supported non-negative univariate
distribution. When `α == ones(d)`, the resulting `LiouvilleCopula` is exactly
the Archimedean copula generated by `G`; evaluation uses that identity while
the concrete Liouville family type is retained.

Sampling and distribution evaluation follow `Distributions.jl`. Selecting
dimensions yields the Liouville copula with the corresponding entries of `α`
and the same mathematical generator. Conditioning and Rosenblatt transforms
use the corresponding conditional distributions. Their numerical algorithms
and intermediate representations are implementation details.

See also the documentation example “Liouville copulas with real Dirichlet
parameters”.

# Example
```julia
using Copulas
using Copulas: ClaytonGenerator

C = LiouvilleCopula(ClaytonGenerator(2.0), (0.8, 1.2, 1.5))
U = rand(C, 100)
```

See also: [`Generator`](@ref), [`ArchimedeanCopula`](@ref), [`𝒲₋₁`](@ref),
[`condition`](@ref), [`subsetdims`](@ref).
"""
struct LiouvilleCopula{d,TG,Tα} <: Copula{d}
    G::TG
    α::NTuple{d,Tα}
    function LiouvilleCopula{d}(G::Generator, α) where {d}
        d >= 2 || throw(ArgumentError("a Liouville copula must have dimension at least 2"))
        length(α) == d || throw(ArgumentError("expected $d Dirichlet parameters, got $(length(α))"))
        αtuple = promote(map(float, α)...)
        all(a -> isfinite(a) && a > 0, αtuple) || throw(ArgumentError("Dirichlet parameters must be finite and positive"))
        α₀ = sum(αtuple)
        _supports_liouville_order(G, α₀) || throw(ArgumentError("the generator $G cannot provide the required Williamson order sum(α) = $α₀"))
        return new{d,typeof(G),eltype(αtuple)}(G, αtuple)
    end
end
Base.eltype(C::LiouvilleCopula) = promote_type(eltype(C.G), eltype(C.α))

LiouvilleCopula(G::Generator, α) = LiouvilleCopula{length(α)}(G, α)
LiouvilleCopula(d::Integer, G::Generator, α) = LiouvilleCopula{d}(G, α)

Distributions.params(C::LiouvilleCopula) = (; G = C.G, α = C.α)

_liouville_order(C::LiouvilleCopula) = sum(C.α)
_liouville_radial(C::LiouvilleCopula) = 𝒲₋₁(C.G, _liouville_order(C))
_liouville_margin(C::LiouvilleCopula, i::Integer) = 𝒲₋₁(C.G, C.α[i])
copula_measure_style(C::LiouvilleCopula) =
    radial_measure_style(C.G, _liouville_order(C))
function _liouville_coordinates(C::LiouvilleCopula{d}, u) where {d}
    margins = ntuple(i -> 𝒲₋₁(C.G, C.α[i]), d)
    x = ntuple(i -> Distributions.quantile(margins[i], 1 - u[i]), d)
    return margins, x
end

function Distributions._rand!(
    rng::Distributions.AbstractRNG,
    C::LiouvilleCopula{d},
    A::AbstractMatrix{T},
) where {d,T<:Real}
    size(A, 1) == d || throw(ArgumentError("Dimension mismatch between copula and output matrix"))
    all(isone, C.α) &&
        return Distributions._rand!(rng, ArchimedeanCopula{d}(C.G), A)
    radial = _liouville_radial(C)
    simplex = Distributions.Dirichlet(collect(C.α))
    margins = ntuple(i -> _liouville_margin(C, i), d)
    direction = Vector{T}(undef, d)

    @inbounds for col in axes(A, 2)
        Random.rand!(rng, simplex, direction)
        r = rand(rng, radial)
        for row in axes(A, 1)
            A[row, col] = Distributions.ccdf(margins[row], r * direction[row])
        end
    end
    return A
end

function _cdf(C::LiouvilleCopula{2}, u)
    all(isone, C.α) && return Distributions.cdf(ArchimedeanCopula{2}(C.G), u)
    isone(u[1]) && return u[2]
    isone(u[2]) && return u[1]
    _, x = _liouville_coordinates(C, u)
    radial = 𝒲₋₁(C.G, _liouville_order(C))
    beta = Distributions.Beta(C.α...)
    xsum = sum(x)

    value = Distributions.expectation(radial) do r
        r <= xsum && return zero(float(r + xsum))
        lo = Distributions.cdf(beta, x[1] / r)
        hi = Distributions.cdf(beta, 1 - x[2] / r)
        return max(zero(hi - lo), hi - lo)
    end
    return clamp(value, zero(value), one(value))
end

function _cdf(C::LiouvilleCopula{d}, u) where {d}
    all(isone, C.α) && return Distributions.cdf(ArchimedeanCopula{d}(C.G), u)

    # Copula margins are exact when one or more coordinates are equal to one.
    # Avoid integrating inactive coordinates numerically.
    active = Tuple(i for i in 1:d if !isone(u[i]))
    isempty(active) && return one(eltype(u))
    length(active) == 1 && return u[active[1]]
    if length(active) < d
        S = subsetdims(C, active)
        v = [u[i] for i in active]
        return Distributions.cdf(S, v)
    end

    # TODO: When all Dirichlet parameters are integers, replace this cubature
    # with the corresponding exact finite-sum expression.
    _, x = _liouville_coordinates(C, u)
    radial = 𝒲₋₁(C.G, _liouville_order(C))
    betas = ntuple(i -> Distributions.Beta(C.α[i], sum(C.α[(i + 1):d])), d - 1)
    T = float(promote_type(eltype(u), eltype(C.α)))

    function integrand(z)
        any(t -> iszero(t) || isone(t), z) && return zero(T)
        remaining = one(T)
        threshold = zero(T)
        @inbounds for i in 1:(d - 1)
            v = Distributions.quantile(betas[i], z[i])
            direction = remaining * v
            threshold = max(threshold, x[i] / direction)
            remaining *= 1 - v
        end
        threshold = max(threshold, x[d] / remaining)
        return Distributions.ccdf(radial, threshold)
    end

    value = HCubature.hcubature(integrand, zeros(T, d - 1), ones(T, d - 1); rtol=sqrt(eps(T)))[1]
    return clamp(value, zero(value), one(value))
end

function Distributions._logpdf(C::LiouvilleCopula{d}, u) where {d}
    all(isone, C.α) && return Distributions.logpdf(ArchimedeanCopula{d}(C.G), u)
    all(x -> 0 < x < 1, u) || return eltype(u)(-Inf)

    radial = 𝒲₋₁(C.G, _liouville_order(C))
    margins, x = _liouville_coordinates(C, u)
    r = sum(x)
    α₀ = _liouville_order(C)
    radial_density = Distributions.pdf(radial, r)
    isfinite(radial_density) && radial_density > 0 || return eltype(u)(-Inf)
    margin_densities = ntuple(i -> Distributions.pdf(margins[i], x[i]), d)
    all(f -> isfinite(f) && f > 0, margin_densities) || return eltype(u)(-Inf)

    value = SpecialFunctions.loggamma(α₀) - sum(SpecialFunctions.loggamma, C.α)
    value += log(radial_density) + (1 - α₀) * log(r)
    value += sum(i -> (C.α[i] - 1) * log(x[i]) - log(margin_densities[i]), 1:d)
    return value
end



_liouville_conditioning_radial(G::Generator, d::Real) = 𝒲₋₁(G, d)


function _liouville_conditional_components(
    C::LiouvilleCopula{D}, js::NTuple{p,Int}, uⱼₛ::NTuple{p,<:Real},
) where {D,p}
    is = Tuple(i for i in 1:D if i ∉ js)
    source_order = _liouville_order(C)
    target_order = sum(C.α[i] for i in is)
    tilted_order = sum(C.α[j] for j in js)
    original_margins = ntuple(i -> _liouville_conditioning_radial(C.G, C.α[i]), D)
    xⱼₛ = ntuple(k -> Distributions.quantile(original_margins[js[k]], 1 - uⱼₛ[k]), p)
    shift = sum(xⱼₛ)

    source_frailty = frailty(C.G)
    conditional_generator = if source_frailty !== nothing && !(source_frailty isa AlphaStable)
        conditional_frailty = PowerTiltedFrailty(source_frailty, tilted_order, shift)
        conditional_radial = WilliamsonFromFrailty(conditional_frailty, target_order)
        𝒲(conditional_radial, target_order)
    elseif isinteger(tilted_order)
        TiltedGenerator(C.G, Int(tilted_order), shift)
    else
        source_radial = _liouville_conditioning_radial(C.G, source_order)
        conditional_radial = LiouvilleConditionalRadial(
            source_radial, shift, source_order, target_order,
        )
        𝒲(conditional_radial, target_order)
    end

    conditional_margins = ntuple(
        k -> 𝒲₋₁(conditional_generator, C.α[is[k]]),
        length(is),
    )
    distortions = ntuple(
        k -> LiouvilleDistortion(original_margins[is[k]], conditional_margins[k]),
        length(is),
    )
    conditional_copula = length(is) == 1 ? nothing : LiouvilleCopula{length(is)}(
        conditional_generator, ntuple(k -> C.α[is[k]], length(is)),
    )
    return conditional_copula, distortions, is
end

function distortion(
    C::LiouvilleCopula,
    js::NTuple{p,Int},
    uⱼₛ::NTuple{p,<:Real},
    i::Int,
) where {p}
    _, distortions, is = _liouville_conditional_components(C, js, uⱼₛ)
    position = findfirst(==(i), is)
    position === nothing && throw(ArgumentError("the target dimension is conditioned"))
    return distortions[position]
end

function conditional_copula(C::LiouvilleCopula, js, uⱼₛ)
    conditional_copula, _, _ = _liouville_conditional_components(C, js, uⱼₛ)
    conditional_copula === nothing && throw(ArgumentError(
        "conditioning leaves one margin and therefore no conditional copula",
    ))
    return conditional_copula
end

# `condition` needs both the conditional copula and all marginal distortions,
# whereas Rosenblatt and one-dimensional conditioning request individual
# distortions through `distortion`. Specializing this shared helper avoids
# rebuilding (and renormalizing) the same conditional frailty or radial once
# for the copula and once per remaining margin. The `conditional_copula` and
# `distortion` methods above remain the family extension points.
function _conditional_components(C::LiouvilleCopula, js, uⱼₛ, is)
    conditional_copula, distortions, computed_is =
        _liouville_conditional_components(C, js, uⱼₛ)
    computed_is == is || throw(ArgumentError("inconsistent conditioning dimensions"))
    return conditional_copula, distortions
end

SubsetCopula(C::LiouvilleCopula, dims::NTuple{p,Int}) where {p} =
    LiouvilleCopula{p}(C.G, ntuple(i -> C.α[dims[i]], p))

_available_fitting_methods(::Type{<:LiouvilleCopula}, d) = Tuple{}()
