name: Benchmark this PR
on:
  pull_request:
      types: [labeled, opened, synchronize, reopened]
permissions:
  pull-requests: write

jobs:
  bench:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run benchmark')
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: '1'