name: Benchmark this PR
on:
  pull_request_target:
    types: [labeled]
    branches: [ main ]
permissions:
  pull-requests: write

jobs:
  bench:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run benchmark')
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: '1'
          bench-on: ${{ github.event.pull_request.head.sha }}
      - name: Remove run benchmark label
        if: ${{ success() }}
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'run benchmark'
              });
            } catch (error) {
              console.log('Label may not exist or already removed');
            }